service: mad-wrapped-api

frameworkVersion: "3"

plugins:
  - serverless-dotenv-plugin
  - serverless-esbuild
  - serverless-offline
  - serverless-domain-manager

provider:
  name: aws
  runtime: nodejs20.x
  region: us-east-1
  stage: ${opt:stage, 'dev'}
  environment:
    STAGE: ${opt:stage, 'dev'}
    MONGODB_URI: ${env:MONGODB_URI, ''}
    MONGODB_DB_NAME: ${env:MONGODB_DB_NAME, ''}
    SENTRY_DSN: ${env:SENTRY_DSN, ''}
    ADMIN_EMAIL: ${env:ADMIN_EMAIL, ''}
    ADMIN_CC_EMAIL: ${env:ADMIN_CC_EMAIL, ''}
    DB_PASSWORD: ${env:DB_PASSWORD, ''}
    DB_SSL: ${env:DB_SSL, ''}
    DB_HOST: ${env:DB_HOST, ''}
    DB_PORT: ${env:DB_PORT, ''}
    DB_NAME: ${env:DB_NAME, ''}
    DB_USER: ${env:DB_USER, ''}
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - ses:SendEmail
            - ses:SendRawEmail
          Resource: "*"

package:
  patterns:
    - "!.git/**"
    - "!.gitignore"
    - "!.serverless/**"
    - "!.vscode/**"
    - "!test/**"
    - "!README.md"
    - "node_modules/**"
    - "!node_modules/.cache/**"
    - "!node_modules/@types/**"
    - "src/**"
    - "package.json"
    - "package-lock.json"
    - "tsconfig.json"
    - "data/**"

functions:
  api:
    handler: src/handler.handler
    timeout: 15
    events:
      - http:
          path: /api/stats/{clientId}/{studioId}
          method: get
          cors: true
      - http:
          path: /api/health
          method: get
          cors: true
      - http:
          path: /api/lookup
          method: post
          cors: true
      - http:
          path: /api/notify-request
          method: post
          cors: true

custom:
  esbuild:
    bundle: true
    minify: false
    sourcemap: true
    exclude:
      - aws-sdk
    external:
      - "@sentry/profiling-node"
    target: node20
    platform: node
    concurrency: 10
  serverless-offline:
    httpPort: 8080
  basePaths:
    production: ""
    dev: "dev"
  customDomain:
    domainName: api.madwrapped.com
    basePath: ${self:custom.basePaths.${self:provider.stage}}
    stage: ${opt:stage, 'dev'}
    createRoute53Record: true
    endpointType: "regional"
    securityPolicy: tls_1_2
    apiType: rest
    autoDomain: true
  dotenv:
    path: .env
    basePath: ./
    include:
      - SENTRY_DSN
      - MONGODB_URI
      - MONGODB_DB_NAME
      - ADMIN_EMAIL
      - ADMIN_CC_EMAIL
      - DB_PASSWORD
      - DB_SSL
      - DB_HOST
      - DB_PORT
      - DB_NAME
      - DB_USER
